---

# Taiga connection
taiga_server_port: 8080
# Determined by $ ip -4 route get 8.8.8.8 // also check out roles/taiga/vars/main.yaml
taiga_server_ip: "{{ ansible_default_ipv4.address }}"
taiga_server_ip_v6: "{{ ansible_default_ipv6.address }}"

# Taiga user / folder structure / .venv
taiga_user: taiga
taiga_group: "{{ taiga_user }}" 
taiga_folder_front: "/home/{{ taiga_user }}/taiga-front-dist"
taiga_folder_back: "/home/{{ taiga_user }}/taiga-back"
taiga_venv: "/home/{{ taiga_user }}/.venv"

# Taiga database settings
# taiga_database_user should match with taiga_user! since postgresql is set up to use "peer" login for any local connection
taiga_database_user: "{{ taiga_user }}"
taiga_database_name: taiga


# GitHub repositories (always stable branch)
taiga_back_repo: https://github.com/stu-ba/taiga-back.git
taiga_front_dist_repo: https://github.com/stu-ba/taiga-front-dist.git

# Systemd uses daemonized gunicorn to serve django app, circus does not.
service_manager: systemd #or circus
