---

# Taiga connection
taiga_port: 8080
taiga_server_ip: hostvars[matrix]['ansible_default_ipv4']['address'] # matrix IP

# Taiga user / folder structure
taiga_user: taiga
taiga_folder_front: "/home/{{taiga_username}}/taiga-front-dist"
taiga_folder_back: "/home/{{taiga_username}}/taiga-back"

# Taiga database settings
taiga_database_user: taiga
taiga_database_name: taiga


# GitHub repositories
taiga_back_repo: https://github.com/stu-ba/taiga-back.git
taiga_front_dist_repo: https://github.com/stu-ba/taiga-front-dist.git

venv_python: "/home/{{taiga_user}}/.venv/bin/python3.5"