---

- name: update pg-hba
  become: yes
  copy:
    src: "{{ role_path }}/files/etc/postgresql/9.4/main/pg_hba.conf.{{ pg_environment | default('production') }}"
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644
    backup: yes
  notify: [restart postgresql]

- name: start yap-queue
  become: yes
  systemd: name=yap-queue.target daemon_reload=yes state=started

- name: stop yap-queue
  become: yes
  systemd: name=yap-queue.target daemon_reload=yes state=stopped

- name: restart yap-queue
  become: yes
  systemd: name=yap-queue.target daemon_reload=yes state=restarted

- name: enable yap-queue
  become: yes
  systemd: name=yap-queue.target daemon_reload=yes state=started enabled=yes

- name: disable yap-queue
  become: yes
  systemd: name=yap-queue.target daemon_reload=yes state=stopped enabled=no
