---

- name: install circus
  become: yes
  pip: 
    name: circus
    state: present

- name: copy circus config file
  become: yes
  template:
    src: "{{ role_path }}/templates/conf/circus.conf.j2"
    dest: /home/{{ taiga_user }}/conf/circus.ini

- name: remove taiga-service config file
  become: yes
  file:
    state: absent
    path: /etc/systemd/system/taiga.service

- name: copy circus service config
  become: yes
  template:
    src: "{{ role_path }}/templates/etc/systemd/system/circus.service.j2"
    dest: /etc/systemd/system/circus.service

- name: enable circus
  become: yes
  systemd: name=circus daemon_reload=yes enabled=yes