---

- name: install dependencies
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - binutils-doc
    - autoconf
    - flex
    - bison
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libzmq3-dev
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - libffi-dev
    - tmux
    - gettext
    - python3
    - python3-pip
    - python-dev
    - python3-dev
    - python-pip
    - virtualenvwrapper
    - libxml2-dev
    - libxslt-dev
  tags: [apt]