---

- name: create postgresql user {{ taiga_user }}
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ taiga_database_user }}"

- name: ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  postgresql_user: 
    name: "{{ taiga_user }}" 
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: create database "{{ taiga_database_user }}"
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ taiga_database_name }}"
    owner: "{{ taiga_database_user }}"
