---

- name: download the code from github
  become: yes
  git:
    repo: "{{ taiga_front_dist_repo }}"
    version: stable
    dest: "{{ taiga_folder_front }}"

- name: install settings templates
  become: yes
  template:
    src: "{{ role_path }}/templates/front/dist/conf.json.j2"
    dest: "{{ taiga_folder_front }}/dist/conf.json"

- name: change owner
  become: yes
  file:
    path: "{{ taiga_folder_front }}"
    state: directory
    recurse: yes
    owner: "{{ taiga_user }}"
    group: "{{ taiga_group }}"