---

- name: remove circus config file
  become: yes
  file:
    state: absent
    path: /home/{{ taiga_user }}/conf/circus.ini

- name: remove circus service unit
  become: yes
  file:
    state: absent
    path: /etc/systemd/system/circus.service

- name: copy taiga service unit
  become: yes
  template:
    src: "{{ role_path }}/templates/etc/systemd/system/taiga.service.j2"
    dest: /etc/systemd/system/taiga.service

- name: add taiga service unit to postgresql wants folder
  become: yes
  file:
    src: /etc/systemd/system/taiga.service
    dest: /etc/systemd/system/postgresql.service.wants/taiga.service
    state: link
    
- name: copy tempfiles.d/taiga.conf
  become: yes
  template:
    src: "{{ role_path }}/templates/usr/lib/tmpfiles.d/taiga.conf.j2"
    dest: /usr/lib/tmpfiles.d/taiga.conf

- name: create /run/taiga folder to store pid file
  become: yes
  file:
    name: /run/taiga
    state: directory
    owner: "{{ taiga_user }}"
    group: "{{ taiga_group }}"

- name: enable taiga-service
  become: yes
  systemd: 
    name: taiga 
    daemon_reload: yes 
    enabled: yes
  notify: 
    - restart taiga-service
