---

- name: download the code from github
  become: yes
  git:
    repo: "{{ taiga_front_dist_repo }}"
    version: stable
    dest: "/home/{{ taiga_user }}/taiga-front-dist"

- name: install settings templates
  become: yes
  template:
    src: "{{ role_path }}/templates/front/dist/conf.json.j2"
    dest: "/home/{{ taiga_user }}/taiga-front-dist/dist/conf.json"

- name: change owner
  become: yes
  file:
    path: "/home/{{ taiga_user }}/taiga-front-dist"
    state: directory
    recurse: yes
    owner: taiga
    group: taiga