---

- name: download the code from github
  become: yes
  become_user: "{{ taiga_user }}"
  git:
    repo: "{{ taiga_front_dist_repo }}"
    version: yap-stable
    dest: "{{ taiga_folder_front }}"

# Load yap variables since we need yap_server_ip
- name: include vars from yap role
  include_vars:
    file: "{{ playbook_dir }}/roles/yap/vars/main.yaml"
    name: yap

- name: include default vars from yap role
  include_vars:
    file: "{{ playbook_dir }}/roles/yap/defaults/main.yaml"
    name: yap
  when: yap_server_ip is not defined

- name: configure settings
  become: yes
  become_user: "{{ taiga_user }}"
  template:
    src: "{{ role_path }}/templates/front/dist/conf.json.j2"
    dest: "{{ taiga_folder_front }}/dist/conf.json"

- name: change owner
  become: yes
  file:
    path: "{{ taiga_folder_front }}"
    state: directory
    recurse: yes
    owner: "{{ taiga_user }}"
    group: "{{ taiga_group }}"
