---

- name: install postgresql
  become: yes
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - postgresql-9.4
    - postgresql-contrib-9.4
    - postgresql-doc-9.4
    - postgresql-server-dev-9.4
    - libpq-dev
    - python-psycopg2 # so we can use ansible postgresql module
  notify: 
    - start postgresql
  tags: [apt]

- name: create postgresql.service.wants folder
  become: yes
  file:
    name: /etc/systemd/system/postgresql.service.wants
    state: directory

- name: touch empty file for postgresql.service.wants folder
  become: yes
  file:
    name: /etc/systemd/system/postgresql.service.wants/empty
    state: touch
    