---

- name: install postgresql
  become: yes
  apt: pkg="{{ item }}" state=present update_cache=no
  with_items:
    - postgresql-9.4
    - postgresql-contrib-9.4
    - postgresql-doc-9.4
    - postgresql-server-dev-9.4
    - libpq-dev
    - python-psycopg2 # so we can use ansible postgresql module
  notify: start postgresql
  tags: [apt]