---

- name: create logs folder
  become: yes
  file:
    name: "/home/{{ yap_user }}/logs"
    state: directory
    owner: "{{ yap_user }}"
    group: "{{ yap_group }}"

- name: add yap site
  become: yes
  template:
    src: "{{ role_path }}/templates/etc/nginx/sites-available/yap.j2"
    dest: "/etc/nginx/sites-available/yap"
  notify:
    - reload nginx

- name: enable yap site config
  become: yes
  file: 
    src: /etc/nginx/sites-available/yap
    dest: /etc/nginx/sites-enabled/yap 
    state: link
  notify:
    - reload nginx
